/:
    template: home.twig

/christelijke-kinderopvang-hoboken:
    template: locations/de-vlam.twig
    variables:
        image1: resources/img/side1.jpg
        image2: resources/img/side4.jpg

/het-vlinderhuisje-hoboken:
    template: locations/het-vlinderhuisje.twig
    variables:
        image1: resources/img/side2.jpg
        image2: resources/img/side3.jpg

/het-speelkasteel:
    template: locations/het-speelkasteel.twig
    variables:
        banner: resources/img/banner.jpg
        image1: resources/img/side1.jpg
        image2: resources/img/side4.jpg
